### ISSUE TITLE
Login Tests

### ISSUE THREAD

**Issue by MikeSmvl** [MikeSmvl/NightWatchJS#1]
As a developer, I want the login feature to have tests to make sure the system does what it is intended to do.

- [x] Successful/Invalid credential login with text validation [#2] 3 SP
- [x] Successful/Invalid credential login with image validation [#3] 8 SP
- [x] Run the tests in parallel 2 SP
- [ ] Run the tests in a docker container 2 SP

[Story Points: 15]
[Risk: low]
[Priority: high]
